export const mainImages = [
  {
    id: "2024-winter-12",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_1.jpg",
  },
  {
    id: "2024-autumn-37",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_2.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_3.jpg",
  },
  {
    id: "2024-autumn-38",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_4.jpg",
  },
  {
    id: "2024-autumn-39",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_5.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_6.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_7.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_8.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_9.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_10.jpg",
  },
  {
    id: "2024-autumn-40",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_11.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_12.jpg",
  },
  {
    id: "2024-autumn-41",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_13.jpg",
  },
  {
    id: "2024-winter-13",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_14.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_15.jpg",
  },
  {
    id: "2024-winter-14",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_16.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_17.jpg",
  },
  {
    id: "2024-winter-15",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_18.jpg",
  },
  {
    id: "2024-winter-16",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_19.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_20.jpg",
  },
  {
    id: "2024-autumn-42",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_21.jpg",
  },
  {
    id: "2024-winter-17",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_22.jpg",
  },
  {
    id: "2024-winter-18",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_23.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_24.jpg",
  },
  {
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_25.jpg",
  },
  {
    id: "2024-autumn-43",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_26.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_27.jpg",
  },
  {
    year: 2023,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_28.jpg",
  },
  {
    id: "2024-autumn-45",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_29.jpg",
  },
  {
    year: 2023,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_30.jpg",
  },
  {
    id: "2024-autumn-44",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_31.jpg",
  },
  {
    id: "2024-autumn-46",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_32.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_33.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_34.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_35.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_36.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_37.jpg",
  },
  {
    year: 2023,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_38.jpg",
  },
  {
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_39.jpg",
  },
  {
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/m_40.jpg",
  },
];

export const galleryImages = [
  {
    id: "2024-winter-01",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_1.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-02",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_2.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-03",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_3.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-04",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_4.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-05",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_5.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-06",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_6.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-07",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_7.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-08",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_8.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-09",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_9.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-10",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_10.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2024-winter-11",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/g_11.jpg",
    year: 2024,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2025-spring-01",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_1.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-02",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_2.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-03",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_3.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-04",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_4.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-05",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_5.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-06",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_6.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-07",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_7.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-08",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_8.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-09",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_9.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-10",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_10.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-11",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_11.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-12",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_12.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-13",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_13.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-14",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_14.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-15",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_15.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-16",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_16.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-17",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_17.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-18",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_18.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-19",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_19.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-20",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_20.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-21",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/s_21.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },

  {
    id: "2025-spring-01",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_1.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-02",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_2.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-03",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_3.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-04",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_4.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-05",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_5.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-06",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_6.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-07",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_7.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-08",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_8.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-09",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_9.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-10",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_10.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-11",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_11.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-12",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_12.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-13",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_13.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-14",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_14.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-15",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_15.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-16",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_16.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-17",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_17.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-18",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_18.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2025-spring-19",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/j_19.jpg",
    year: 2025,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },

  {
    id: "2024-autumn-01",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_1.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-02",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_2.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-03",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_3.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-04",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_4.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-05",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_5.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-06",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_6.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-07",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_7.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-08",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_8.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-09",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_9.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-10",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_10.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-11",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_11.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-12",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_12.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-13",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_13.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-14",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_14.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-15",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_15.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-16",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_16.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-17",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_17.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-18",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_18.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-19",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_19.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-20",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_20.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-21",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_21.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-22",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_22.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-23",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_23.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-24",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_24.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-25",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_25.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-26",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_26.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-27",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_27.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-28",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_28.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-29",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_29.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-30",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_30.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-31",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_31.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-32",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_32.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-33",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_33.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-34",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_34.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-35",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_35.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2024-autumn-36",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/t_36.jpg",
    year: 2024,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-1",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_1.jpg",
    year: 2023,
    season: "summer",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-2",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_2.jpg",
    year: 2024,
    season: "summer",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-3",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_3.jpg",
    year: 2023,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-4",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_4.jpg",
    year: 2023,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-5",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_5.jpg",
    year: 2023,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-6",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_6.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-7",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_7.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-8",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_8.jpg",
    year: 2024,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-9",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_9.jpg",
    year: 2024,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-10",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_10.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-11",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_11.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-12",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_12.jpg",
    year: 2023,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-13",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_13.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-14",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_14.jpg",
    year: 2024,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-15",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_15.jpg",
    year: 2024,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-16",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_16.jpg",
    year: 2024,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-17",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_17.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-18",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_18.jpg",
    year: 2023,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-19",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_19.jpg",
    year: 2023,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-20",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_20.jpg",
    year: 2024,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-21",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_21.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-22",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_22.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-23",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_23.jpg",
    year: 2024,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-24",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_24.jpg",
    year: 2023,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-25",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_25.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-26",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_26.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
  {
    id: "2023-spring-27",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_27.jpg",
    year: 2024,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-28",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_28.jpg",
    year: 2024,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-29",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_29.jpg",
    year: 2024,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-30",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_30.jpg",
    year: 2024,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-31",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_31.jpg",
    year: 2024,
    season: "summer",
    seasonKr: "여름",
    alt: "웨딩",
  },
  {
    id: "2023-spring-32",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_32.jpg",
    year: 2024,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-33",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_33.jpg",
    year: 2023,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-34",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_34.jpg",
    year: 2023,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-35",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_35.jpg",
    year: 2024,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-36",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_36.jpg",
    year: 2024,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-37",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_37.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-38",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_38.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-39",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_39.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-40",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_40.jpg",
    year: 2024,
    season: "spring",
    seasonKr: "봄",
    alt: "웨딩",
  },
  {
    id: "2023-spring-41",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_41.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-42",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_42.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-43",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_43.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-44",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_44.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-45",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_45.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-45",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_46.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-45",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_47.jpg",
    year: 2023,
    season: "autumn",
    seasonKr: "가을",
    alt: "웨딩",
  },
  {
    id: "2023-spring-45",
    src: "https://d11ay48rmhjgmh.cloudfront.net/wedding/o_48.jpg",
    year: 2023,
    season: "winter",
    seasonKr: "겨울",
    alt: "웨딩",
  },
];

// 2023 봄: 45개

// 2023 여름: 2개

// 2024 가을: 46개

// 2024 겨울: 19개

// 2025 봄: 58개
